name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@2.0.0
    with:
      library: libhal-__platform__
      coverage: true
    secrets: inherit
